[package]
name = "app"
version = "0.1.0"
authors = ["Ryan Brewster <ryanpbrewster@google.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"

[dependencies]
failure = "*"
stdweb = "0.4"
wasm-bindgen = "0.2"
yew = "0.10"
isort = { path = "../isort" }
